# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: db-dev
      POSTGRES_PASSWORD: DATABASE_PASSWORD
    ports:
        - 5432:5432
    networks:
      - test_default

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - test_default

  app:
    image: tech-challenge:dev
    ports:
      - "3000:3000"
    volumes:
      - ../..:/app/back-end/apis/nestjs
    networks:
      - test_default
    depends_on:
      - db
    environment:
      DATABASE_HOST: "db"  # Replace with the host machine's IP address
      DATABASE_PORT: 5432
      DATABASE_USER: "postgres"
      DATABASE_PASSWORD: "DATABASE_PASSWORD"
      DATABASE_NAME: "db-dev"
      DATABASE_SYNC: 1
      DATABASE_LOG_ENABLE: 0
      DATABASE_DROP_SCHEMA: 1
      PAG_BANK_BEARER_TOKEN: "EEF14D9AE30846E0BF6F189445AECA7B"
      WEBHOOK_CRIAR_PEDIDO_URL: ""
networks:
  test_default: