# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    user: user:user
    restart: always
    environment:
      POSTGRES_DB: db
      POSTGRES_PASSWORD: DATABASE_PASSWORD
    ports:
        - 5432:5432
    networks:
      - test_default

  app:
    image: tech-challenge:v1
    ports:
      - "3000:3000"
    networks:
      - test_default
    depends_on:
      - db
    environment:
      DATABASE_HOST: "db"  # Replace with the host machine's IP address
      DATABASE_PORT: 5432
      DATABASE_USER: "postgres"
      DATABASE_PASSWORD: "DATABASE_PASSWORD"
      DATABASE_NAME: "db"
      DATABASE_SYNC: 0
      DATABASE_LOG_ENABLE: 0
      DATABASE_DROP_SCHEMA: 0
      PAG_BANK_BEARER_TOKEN: ""
networks:
  test_default: