# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    env_file:
      - .env
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: db-dev
      POSTGRES_PASSWORD: DATABASE_PASSWORD
    ports:
        - 5432:5432